export const NiftronUserLambda = "https://32o47h3pc2.execute-api.us-east-1.amazonaws.com/prod";
export const NiftronTokenLambda = "https://y548z5pqmi.execute-api.us-east-1.amazonaws.com/prod";
export const NiftronAPI = "https://api.niftron.com";
export const StellarUrlTest= "https://horizon-testnet.stellar.org"
export const StellarUrl= "https://horizon.stellar.org"
export const StellarNetwork="TestNet"
export const Version="0.01"
export const NiftronIssuerPublicKey="GBIV5P2STT7M7633B4IU54MUFBKWELUX5J7ELA5QBXUGRXM4MQYKJHE7"
export const NiftronDistributorPublicKey="GCC4PL7FJJ74DGVAU3ODHU4HPU7E6CNQ6XMMV3CKEC4GFB4QG3W4L7ZF"
export const PatternPK = /^[G,g][a-zA-Z0-9]{55}$/;
export const PatternSK = /^[S,s][a-zA-Z0-9]{55}$/;
export const PatternId = /^[S,N,s,n][T,N,t,n][T,N,t,n][A,N,a,n][a-zA-Z0-9][T,N,t,n][a-zA-Z0-9]{6}$/;